# Generated by Django 5.1.6 on 2025-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starF', '0002_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(),
        ),
    ]
